ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN invited_by BIGINT REFERENCES users(id);
ALTER TABLE affiliations ADD COLUMN contact_email VARCHAR(255);
ALTER TABLE affiliations ADD COLUMN contact_phone VARCHAR(255);
ALTER TABLE affiliations ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();
